// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhI0sc3h5lN-JnEE5AV_-v12Bz86FB9ik',
    appId: '1:508546222147:android:3d2c580372ca8d6e766cf6',
    messagingSenderId: '508546222147',
    projectId: 'lock-628be',
    databaseURL: 'https://lock-628be-default-rtdb.firebaseio.com',
    storageBucket: 'lock-628be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACby05KRPHODZnqzYA_iTksAWvACrupV0',
    appId: 'app-1-508546222147-ios-adf08fecb0ee3196766cf6',
    messagingSenderId: '508546222147',
    projectId: 'lock-628be',
    databaseURL: 'https://lock-628be-default-rtdb.firebaseio.com',
    storageBucket: 'lock-628be.appspot.com',
    androidClientId:
        '508546222147-04jj1urqieq909oms6lo9d1c2dn760v0.apps.googleusercontent.com',
    iosBundleId: 'ios.lock.customer',
  );
}
